name: Generate File List

on:
  push:
    branches:
      - main  # Change to your branch name

jobs:
  generate_file_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate file list
        run: |
          echo "## File List" > README.md
          # find . -type f | sed 's/^.\{2\}//' | awk '{print "* [" $0 "](./" $0 ")"}' >> README.md
          find docs -type f | sed 's/^docs\///' | awk '{print "* [/" "docs/" $0 "](./" "docs/" $0 ")"}' >> README.md
          echo "#### Last Update: $(TZ='Asia/Kolkata' date)" >> README.md

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update file list [skip ci]"
          git push origin HEAD:${{ github.ref }}
